"""empty message

Revision ID: 425fd543121a
Revises: 673e4b34b034
Create Date: 2025-11-18 07:39:01.989312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425fd543121a'
down_revision = '673e4b34b034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_contact_uc', ['name', 'contact_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('_name_contact_uc', type_='unique')

    # ### end Alembic commands ###
